name: darttv
description: A sample WebUI application
dependencies:
  #oauth2: any
  oic_client:
    path: ../oic_client
  js: any
  browser: any
  web_ui: any
  widget: any
  google_oauth2_client: any
